[default]
# chunking
chunker = "recursive"
chunk_size = 1500
chunk_overlap = 200

# dense retriever
dense_retriever_name = "sentence-transformers/all-MiniLM-L6-v2"

# causal model
causal_model_name = "HuggingFaceM4/idefics2-8b-chatty"

# vector store
vector_store = "chromadb"
retrieve_n = 5
hybrid = true

# lancedb
embbeding_dim = 512

# database
database_path = "database"
database_name = "my_store"
