[default]
# chunking
chunk_size = 450
chunk_overlap = 0

# dense retriever
dense_retriever_name = "jinaai/jina-clip-v1"

# vector store
vector_store = "chromadb"
hybrid = true

# lancedb
embbeding_dim = 512

# chromadb
chroma_db_path = "database"
chroma_collection_name = "my_store"
